# Navigation Links
#   To link a homepage section, use a hash `#` followed by the section ID.
#   The weight parameter defines the order that the links appear.

main:
  - name: Experience
    url: /#experience
    weight: 10

  - name: Recommendations
    url: /#recommendations
    weight: 20

  - name: Publications
    url: /#publications
    weight: 30

  - name: Awards
    url: /#awards
    weight: 40

  - name: Tech Stack
    url: /#tech-stack
    weight: 50
  
  - name: Skills
    url: /#skills
    weight: 60

  - name: Accomplishments
    url: /#accomplishments
    weight: 70

  - name: Contact
    url: /#contact
    weight: 100
